---
# vim: set ft=ansible et ts=2 sw=2:
#
# Get facts about vmware env
- hosts: -- ip --
  connection: local
  gather_facts: False
  remote_user: root 

  tasks:
      - name: get facts
        vmware_guest_facts:
          hostname: -- ip --
          username: username 
          password: password
          datacenter: Datacenter
          uuid: "{{ uuid }}"
          validate_certs: False
        delegate_to: localhost
        register: vm_facts
