---
# vim: set ft=ansible et ts=2 sw=2:
# TO DO: Pass password through vault. 
# Create a new VM from a template

- name: VM from template
  hosts: esxi
  gather_facts: false
  connection: local
  vars:
    vcenter_hostname: <ip address>
    esxhost: "{{ host }}" 
    datastore: "{{ host }}"
    network: "Oasis360"
    vmtemplate: "Template - W2012R2 S2012" 
    vmcluster: LAN
    dumpfacts: False
  tasks:
   # - name: Check for required variables
   #   fail: msg="Must pass name and group to -e"
   #   when: name is not defined or group is not defined

   # - name: Check for vSphere access parameters
   #   fail: msg="Must set vcenter_user and vcenter_pass in a Vault"
   #   when: (vcenter_user is not defined) or (vcenter_pass is not defined)

    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: <ip address>
        username: "{{ user }}"
        password: "{{ password }}"
        esxi_hostname: "{{ host }}"
        datacenter: Datacenter
        folder: Templates
        name: "{{ item }}"
        annotation: Created by ansible
        template: "{{ vmtemplate }}"
        networks:
        - name: "{{ network }}"
        hardware: 
          memory_mb: "{{ vm_memory }}"
          num_cpus: "{{ cpu }}"
        disk:
          size_gb: "{{ disk }}" 
          type: thin
          datastore: "{{ data }}"
        wait_for_ip_address: True
        state: present
      register: newvm
      with_items:
         - TestVM1
         - TestVM2
