---
# vim: set ft=ansible et ts=2 sw=2:
# To Do: add variables
# Get facts about vmware env
- hosts: -- ip --
  connection: local
  gather_facts: False
  remote_user: root 

  tasks:
      - name: get facts
        vmware_vm_facts:
          hostname: -- ip --
          username: username
          password: password
          vm_type: template
          validate_certs: False
        delegate_to: localhost
        register: vm_facts
